name: Deploy server  to vercel on push 
on:
    push:
        branches:
            - deploy
            - feat/221-deploy-application

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
        steps:
            - uses: actions/checkout@v4
            
            - uses: pnpm/action-setup@v4
              with:
                version: 9

            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'pnpm'

            - name: Install deps
              run:  pnpm install --frozen-lockfile

            - name: Build app
              run: pnpm run build:deploy

            - uses: amondnet/vercel-action@v20
              id: vercel-deploy
              with:
                vercel-token: ${{secrets.VERCEL_TOKEN}}
                github-token: ${{secrets.GITHUB_TOKEN}}
                vercel-args: '--prod --prebuilt'
                vercel-org-id: ${{secrets.ORG_ID}}
                vercel-project-id: ${{secrets.PROJECT_ID}}
            - name: preview-url
              run: |
                echo ${{steps.vercel-deploy.outputs.preview-url}}